### ISSUE TITLE
Error when going to settings before the page is fully loaded

### ISSUE THREAD

**Issue by AdamJedl** [matous-volf/rozvrh#47]
Unexpected Application Error!
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at Wl (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:98:166192)
    at ir (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:98:166462)
    at ql (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:98:181797)
    at new n (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:98:184719)
    at CE (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:38:10971)
    at gm (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:40:3385)
    at Ay (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:40:44818)
    at fy (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:40:39724)
    at xS (https://rozvrh.matousvolf.cz/assets/index-b9f41dc2.js:40:39652)

**Comment by matous-volf** [comment]
This also happens when you just visit the settings route before the main one. It is caused by trying to read the not yet created default cookies.

**Comment by matous-volf** [comment]
@AdamJedl i think it doesn't happen anymore. can you confirm? it's been probably fixed by #51.

**Comment by AdamJedl** [comment]
@matous-volf  Yes, it’s fixed
